---
# Role tasks

- name: Setup audit config file
  template:
    src: auditd.conf.j2
    dest: "{{ audit_conf_path }}"

- name: Setup audit sysconfig file
  lineinfile:
    path: "{{ audit_sysconfig_path }}"
    regexp: '^USE_AUGENRULES=\"no\"'
    line: USE_AUGENRULES="yes"
    backrefs: yes
  when: ansible_facts.service_mgr != "systemd"

- name: Setup audit rules
  lineinfile:
    path: "{{ audit_rules_dir }}/{{ audit_item.0.file }}"
    regexp: >-
      {{ (audit_item.1.state == "present")
         | ternary(omit, audit_item.1.rule) }}
    line: >-
      {{ (audit_item.1.state == "present")
         | ternary(audit_item.1.rule, omit) }}
    create: yes
    state: "{{ audit_item.1.state }}"
  register: audit_setup_rules_result
  loop: "{{ audit_rules | subelements('content') }}"
  loop_control:
    loop_var: audit_item
    index_var: audit_index
    label: >-
      {{ audit_item.0.file }}
      {{ audit_index }}
  notify: restart auditd

- name: Merge audit rules files
  command: augenrules
  when:
    - ansible_facts.distribution_major_version is version("6", "==")
    - audit_setup_rules_result.results | select("changed") | list | length > 0

- name: Setup logrotate configuration file
  template:
    src: logrotate.j2
    dest: "{{ audit_logrotate_config_path }}"
  when: audit_logrotate_config_path | default("") | length > 0
