---
# Role tasks

- name: Install required packages
  include_tasks: install_rhel_centos.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"

- name: configure template file
  set_fact:
    audit_conf_file: templates/audit_config-Centos-6.j2
  when: ansible_distribution == "CentOS"
        ansible_distribution_version == 6

- name: configuring audit service
  template:
    src: audit_config.j2
    dest: "{{ audit_conf_file }}"

- debug:
    var: audit_template_file
    verbosity: 2

- name: configuring audit rules from template file
  template:
    src: "{{ audit_template_file }}"
    dest: "{{ audit_rules_file }}"
  when: audit_template_file is defined and audit_template_file is not none
  notify: restart auditd

- name: restart audit service
  meta: flush_handlers
