---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 27
      rhel: 6

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      all:
        all:
          audit: present
          initscripts: present

- include_role:
    name: amtega.sysctl
  vars:
    sysctl:
      - name: disable_console_log
        options:
         - name: kernel.printk
           value: 3 4 1 7
           state: present
           reload: yes

- name: Setup audit config file
  template:
    src: config.j2
    dest: "{{ audit_conf_path }}"

- name: Setup audit sysconfig file
  lineinfile:
    path: "{{ audit_sysconfig_path }}"
    regexp: '^USE_AUGENRULES=\"no\"'
    line: USE_AUGENRULES="yes"
    backrefs: yes
  when: ansible_facts.service_mgr != "systemd"

- name: Setup audit rules
  lineinfile:
    path: "{{ audit_rules_dir }}/{{ audit_item.0.file }}"
    regexp: >-
      {{ (audit_item.1.state == "present")
         | ternary(omit, audit_item.1.rule) }}
    line: >-
      {{ (audit_item.1.state == "present")
         | ternary(audit_item.1.rule, omit) }}
    create: yes
    state: "{{ audit_item.1.state }}"
  loop: "{{ audit_rules | subelements('content') }}"
  loop_control:
    loop_var: audit_item
    index_var: audit_index
    label: >-
      {{ audit_item.0.file }}
      {{ audit_index }}
  notify: restart auditd

- name: Merge audit rules files
  command: augenrules
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == 6
