---
# Role tasks

- name: Setup audit config file
  template:
    src: config.j2
    dest: "{{ audit_conf_path }}"

- name: Setup audit sysconfig file
  lineinfile:
    path: "{{ audit_sysconfig_path }}"
    regexp: '^USE_AUGENRULES=\"no\"'
    line: USE_AUGENRULES="yes"
    backrefs: yes
  when: ansible_facts.service_mgr != "systemd"

- name: Setup audit rules
  lineinfile:
    path: "{{ audit_rules_dir }}/{{ audit_item.0.file }}"
    regexp: >-
      {{ (audit_item.1.state == "present")
         | ternary(omit, audit_item.1.rule) }}
    line: >-
      {{ (audit_item.1.state == "present")
         | ternary(audit_item.1.rule, omit) }}
    create: yes
    state: "{{ audit_item.1.state }}"
  loop: "{{ audit_rules | subelements('content') }}"
  loop_control:
    loop_var: audit_item
    index_var: audit_index
    label: >-
      {{ audit_item.0.file }}
      {{ audit_index }}
  notify: restart auditd

- name: Enable and start auditd
  service:
    name: auditd
    enabled: yes
    state: started
