---
# Role handlers

- name: Restart auditd
  ansible.builtin.command: >-
    {{ auditd_service_ansible.builtin.command }} auditd restart
  args:
    warn: no
  listen: restart auditd
  vars:
    auditd_service_command: >-
      {{ (ansible_facts.distribution_major_version is version("6", ">"))
         | ternary("/usr/sbin/service", "/sbin/service") }}
