---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    box: centos/6
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
  - name: "centos8-${INSTANCE_UUID:-1}"
    box: centos/8
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
  - name: "fedora33-${INSTANCE_UUID:-1}"
    box: fedora/33-cloud-base
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
  - name: "fedora34-${INSTANCE_UUID:-1}"
    box: fedora/34-cloud-base
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          audit_local_events: no
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
